[package]
name = "query-language"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
strsim = "0.10.0"
regex = "1.6.0"
time = { version = "0.3.11", features = ["parsing"] }
thiserror = "1.0.31"