[package]
name = "query-language"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
time = "0.3.5"
regex = "1.6.0"
nom = "7.1.1"